# Dockerfile.v0 — línea base INGENUA
FROM python:3.12

WORKDIR /app

# Copiamos usando la carpeta "scr" del repositorio
COPY src/ /app/src/
COPY requirements.txt /app/

RUN pip install -r requirements.txt

CMD ["python", "src/receptor.py"]
